name: Atualizador de Stream

on:
  schedule:
    - cron: '*/15 * * * *' # Executa o robô a cada 15 minutos automaticamente
  workflow_dispatch: # Permite que você ative o robô manualmente se quiser

jobs:
  atualizar:
    runs-on: ubuntu-latest
    steps:
    - name: Baixar arquivos do repositorio
      uses: actions/checkout@v3

    - name: Configurar o Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Instalar ferramentas de captura
      run: pip install requests beautifulsoup4

    - name: Rodar o robo capturador
      run: python captura.py

    - name: Salvar o link atualizado no GitHub
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add live.m3u8
        git commit -m "Stream atualizada automaticamente" || exit 0
        git push
