name: Stream

on:
  workflow_dispatch:

jobs:
  run-stream:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Instalar Dependencias do Sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg pulseaudio xvfb curl

      - name: Instalar Playwright e Ngrok
        run: |
          pip install playwright pyngrok
          playwright install chromium --with-deps

      - name: Iniciar Transmissao e Servidor
        run: |
          mkdir -p stream
          # Inicia a tela e o som virtual direto na máquina e roda o script
          xvfb-run --server-args="-screen 0 1280x720x24" pulseaudio -D --exit-idle-time=-1 && python app.py
