name: Stream

on:
  workflow_dispatch:

jobs:
  run-stream:
    runs-on: ubuntu-24.04

    timeout-minutes: 350

    steps:

      - name: Baixar código
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: |
          sudo apt-get update

          sudo apt-get install -y \
            ffmpeg \
            pulseaudio \
            xvfb \
            chromium \
            python3-pip \
            python3-dev \
            libnss3 \
            libatk-bridge2.0-0 \
            libgtk-3-0 \
            libgbm1 \
            libasound2t64

      - name: Instalar Python
        run: |
          python3 -m pip install --upgrade pip

          pip install \
            playwright \
            pyngrok

      - name: Verificar Chromium
        run: |
          which chromium
          chromium --version

      - name: Verificar FFmpeg
        run: |
          ffmpeg -version | head -n 1

      - name: Iniciar transmissão
        env:
          PYTHONUNBUFFERED: "1"
        run: |
          python3 app.py
