name: WEBTV 24H

on:
  workflow_dispatch:

  schedule:
    - cron: "0 */4 * * *"

permissions:
  contents: read

jobs:

  webtv:

    runs-on: ubuntu-latest

    timeout-minutes: 290

    steps:

      - name: Baixar código
        uses: actions/checkout@v4

      - name: Instalar dependências
        shell: bash
        run: |
          set -e

          sudo apt-get update

          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y \
            ffmpeg \
            xvfb \
            pulseaudio \
            pulseaudio-utils \
            chromium-browser \
            xdotool \
            curl

      - name: Verificar instalações
        shell: bash
        run: |
          echo "FFmpeg:"
          ffmpeg -version | head -n 1

          echo "Xvfb:"
          Xvfb -help >/dev/null 2>&1 || true

          echo "PulseAudio:"
          pulseaudio --version

          echo "Chromium:"
          chromium-browser --version || chromium --version

      - name: Iniciar WEBTV
        shell: bash
        run: |
          python3 app.py
